import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router";
import { afterEach, describe, expect, it, vi } from "vitest";

import { AutomationCreate, AutomationDetail, Automations, NotificationInbox } from "./Automations";

const ID="11111111-1111-4111-8111-111111111111";
const OCC="22222222-2222-4222-8222-222222222222";
const RUN="33333333-3333-4333-8333-333333333333";
const NOTICE="44444444-4444-4444-8444-444444444444";
const automation={id:ID,label:"Morning brief",automation_kind:"scheduled_agent",agent_kind:"daily_brief",agent_version:"1",project_id:null,lifecycle:"paused",revision:4,execution_mode:"create_only",schedule_kind:"daily",timezone_name:"Asia/Jerusalem",local_time:"08:30:00",one_time_local_date:null,weekdays:[],interval_count:1,nonexistent_time_policy:"first_valid_after_gap",ambiguous_time_policy:"earlier_fold",missed_run_policy:"skip",retry_limit:3,capacity_limit:1,schedule_revision:1,next_occurrence_at:"2026-08-27T05:30:00Z",created_at:"2026-08-20T00:00:00Z",updated_at:"2026-08-21T00:00:00Z",cancelled_at:null};
const occurrence={id:OCC,scheduled_at:"2026-08-26T05:30:00Z",scheduled_local_date:"2026-08-26",scheduled_local_time:"08:30:00",scheduled_utc_offset_minutes:180,timezone_name:"Asia/Jerusalem",state:"failed",attempt_count:3,retry_not_before:null,safe_disposition_code:"operator_review_required",safe_error_code:"setup_retry_exhausted",agent_run_id:RUN,created_at:"2026-08-26T05:30:00Z",claimed_at:"2026-08-26T05:30:01Z",completed_at:"2026-08-26T05:31:00Z"};
const point={local_date:"2026-08-27",local_time:"08:30:00",timezone_name:"Asia/Jerusalem",utc_offset_minutes:180,utc_instant:"2026-08-27T05:30:00Z"};
function response(body:unknown,status=200):Response{return {ok:status>=200&&status<300,status,json:vi.fn().mockResolvedValue(body)} as unknown as Response}
afterEach(()=>{cleanup();vi.unstubAllGlobals()});

describe("Automations operator experience",()=>{
  it("lists lifecycle, scope, mode, schedule, and uses explicit refresh without polling",async()=>{const fetchMock=vi.fn().mockResolvedValue(response([automation]));vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter><Automations/></MemoryRouter>);expect(await screen.findByRole("link",{name:"Morning brief"})).toBeInTheDocument();expect(screen.getByText(/Status: paused/)).toBeInTheDocument();expect(screen.getByText(/Scope: Unassigned/)).toBeInTheDocument();await new Promise(r=>setTimeout(r,30));expect(fetchMock).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole("button",{name:"Refresh"}));expect(fetchMock).toHaveBeenCalledTimes(2)});

  it("requires preview, explains DST and create-only, and submits a draft",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(response([point])).mockResolvedValueOnce(response({...automation,lifecycle:"draft",revision:0}));vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter><Routes><Route path="*" element={<AutomationCreate/>}/></Routes></MemoryRouter>);expect(screen.getByText(/DST gap: the first valid instant/)).toBeInTheDocument();expect(screen.getByText(/create_only:/)).toBeInTheDocument();await userEvent.type(screen.getByLabelText("Label"),"Morning brief");await userEvent.click(screen.getByRole("button",{name:"Create draft"}));expect(await screen.findByRole("alert")).toHaveTextContent("Preview");await userEvent.click(screen.getByRole("button",{name:/Preview next 5/}));expect(await screen.findByText(/UTC\+03:00/)).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Create draft"}));expect(fetchMock.mock.calls[1][1]).toMatchObject({method:"POST"});expect(JSON.parse(String(fetchMock.mock.calls[1][1].body))).toMatchObject({execution_mode:"create_only"})});

  it("shows history linked Run, unavailable automatic mode, and preserves conflict awareness",async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(response(automation)).mockResolvedValueOnce(response([occurrence])).mockResolvedValueOnce(response([point])).mockResolvedValueOnce(response({detail:"automation revision conflict"},409));vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter initialEntries={[`/automations/${ID}`]}><Routes><Route path="/automations/:automationId" element={<AutomationDetail/>}/></Routes></MemoryRouter>);expect(await screen.findByRole("heading",{name:"Morning brief"})).toBeInTheDocument();expect(screen.getByRole("link",{name:"Open linked Agent Run"})).toHaveAttribute("href",`/agents/${RUN}`);expect(screen.getByRole("button",{name:"Use automatic read-only"})).toBeEnabled();await userEvent.click(screen.getByRole("button",{name:/Preview next 5/}));await userEvent.click(screen.getByRole("button",{name:"Save revision-aware edits"}));expect(await screen.findByRole("alert")).toHaveTextContent(/Refresh before retrying/);expect(screen.getByDisplayValue("Morning brief")).toBeInTheDocument()});

  it("renders a content-free inbox and repeated mark-read is an explicit action",async()=>{const notice={id:NOTICE,automation_id:ID,occurrence_id:OCC,agent_run_id:RUN,event_kind:"occurrence_failed",severity:"error",title:"Automation needs review",body:"Open Automation history for safe status.",read_at:null,created_at:"2026-08-26T06:00:00Z"};const read={...notice,read_at:"2026-08-26T06:01:00Z"};const fetchMock=vi.fn().mockResolvedValueOnce(response([notice])).mockResolvedValueOnce(response(read));vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter><NotificationInbox/></MemoryRouter>);expect(await screen.findByText("Automation needs review")).toBeInTheDocument();expect(document.body).not.toHaveTextContent("provider");await userEvent.click(screen.getByRole("button",{name:"Mark read"}));expect(await screen.findByText("Notification marked read.")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Mark read"})).not.toBeInTheDocument();expect(localStorage.length).toBe(0)});
});
