import { FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router";

import { confirmExternalItemImport, createConnectorRefreshSchedule, getConnectorRefreshSchedule, getExternalItem, listConnectorAccounts, listConnectorRefreshOccurrences, listExternalItems, listExternalItemVersions, listProjects, previewExternalItemImport, refreshConnectorAccount, transitionConnectorRefreshSchedule, type ConnectorAccount, type ConnectorRefreshOccurrence, type ConnectorRefreshSchedule, type ExternalItem, type ExternalItemImportPreview, type ExternalItemImportRead, type ProjectRead } from "./api/client";

const stamp = (value: string | null) => value ? new Date(value).toISOString() : "Not available";
const scopeOf = (account: ConnectorAccount) => account.scope.kind === "unassigned" ? "unassigned" : account.scope.project_id!;
const contentText = (item: ExternalItem) => item.content.kind === "repository" ? item.content.description ?? "No description." : item.content.body || "No body.";

export function ExternalContext() {
  const [accounts, setAccounts] = useState<ConnectorAccount[]>([]), [projects, setProjects] = useState<ProjectRead[]>([]);
  const [accountId, setAccountId] = useState(""), [scope, setScope] = useState("unassigned"), [resourceType, setResourceType] = useState(""), [filterState, setFilterState] = useState("");
  const [items, setItems] = useState<ExternalItem[]>([]), [cursor, setCursor] = useState<string | null>(null), [state, setState] = useState("loading"), [message, setMessage] = useState("");
  useEffect(() => { const c = new AbortController(); Promise.all([listConnectorAccounts(c.signal), listProjects(100, 0, c.signal)]).then(([a, p]) => { setAccounts(a); setProjects(p); if (a[0]) { setAccountId(a[0].id); setScope(scopeOf(a[0])); } setState("ready"); }).catch(() => { if (!c.signal.aborted) setState("error"); }); return () => c.abort(); }, []);
  async function load(event?: FormEvent, next?: string) { event?.preventDefault(); if (!accountId) return; setState("loading"); setMessage(""); try { const page = await listExternalItems(accountId, scope, { resourceType: resourceType || undefined, state: filterState || undefined, cursor: next }); setItems(page.items); setCursor(page.next_cursor); setState("ready"); } catch { setItems([]); setCursor(null); setState("error"); } }
  async function refresh() { const account = accounts.find(value => value.id === accountId); if (!account || account.lifecycle !== "enabled") return; setMessage("Refreshing GitHub explicitly…"); try { const run = await refreshConnectorAccount(account.id, account.revision); setMessage(`Manual refresh ${run.status}; reconciliation ${run.reconciliation_complete ? "complete" : "not complete"}.`); if (run.status === "succeeded") await load(); } catch { setMessage("Manual refresh failed safely. Existing external context was preserved."); } }
  return <><header className="page-header"><p className="eyebrow">External / Untrusted</p><h1>External Context</h1><p>Review quarantined GitHub snapshots. Text is displayed literally and never treated as instructions.</p></header><p role="status" aria-live="polite">{message}</p><form className="panel filter-grid" onSubmit={event => void load(event)}><label htmlFor="external-account">Account</label><select id="external-account" value={accountId} onChange={event => { const id = event.target.value; setAccountId(id); const account = accounts.find(value => value.id === id); if (account) setScope(scopeOf(account)); }}><option value="">Select an account</option>{accounts.map(account => <option key={account.id} value={account.id}>{account.external_account_identity}</option>)}</select><label htmlFor="external-scope">Exact scope</label><select id="external-scope" value={scope} onChange={event => setScope(event.target.value)}><option value="unassigned">Explicitly unassigned</option>{projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select><label htmlFor="external-type">Resource type</label><select id="external-type" value={resourceType} onChange={event => setResourceType(event.target.value)}><option value="">All approved types</option><option value="repository">Repository</option><option value="issue">Issue</option><option value="pull_request">Pull request</option></select><label htmlFor="external-state">Reconciliation state</label><select id="external-state" value={filterState} onChange={event => setFilterState(event.target.value)}><option value="">All states</option><option value="current">Current</option><option value="stale">Stale</option><option value="deleted">Deleted</option></select><div className="actions"><button type="submit" disabled={!accountId}>Load external context</button><button type="button" disabled={accounts.find(value => value.id === accountId)?.lifecycle !== "enabled"} onClick={() => void refresh()}>Refresh GitHub manually</button></div></form><section className="panel" aria-busy={state === "loading"}><h2>Latest snapshots only</h2>{state === "loading" && <p>Loading external context…</p>}{state === "error" && <p>External context could not be loaded for that exact account and scope.</p>}{state === "ready" && items.length === 0 && <p>No external snapshots in this exact scope.</p>}<ul className="connector-list">{items.map(item => <li key={item.id}><p className="eyebrow">External / Untrusted · {item.reconciliation_state}</p><h3>{item.title}</h3><p>{item.resource_type.replace("_", " ")} · revision {item.application_revision}</p><p className="external-preview">{contentText(item)}</p><Link to={`/external-context/${item.account_id}/${item.id}?scope=${encodeURIComponent(scope)}`}>Review snapshot and history</Link></li>)}</ul>{cursor && <button type="button" onClick={() => void load(undefined, cursor)}>Next page</button>}</section></>;
}

export function ExternalContextDetail() {
  const { accountId = "", itemId = "" } = useParams(), scope = new URLSearchParams(window.location.search).get("scope") ?? "";
  const [item, setItem] = useState<ExternalItem | null>(null), [versions, setVersions] = useState<ExternalItem[]>([]), [state, setState] = useState("loading");
  const [importPreview, setImportPreview] = useState<ExternalItemImportPreview | null>(null), [importResult, setImportResult] = useState<ExternalItemImportRead | null>(null), [importState, setImportState] = useState("idle");
  useEffect(() => { const c = new AbortController(); Promise.all([getExternalItem(accountId, itemId, scope, c.signal), listExternalItemVersions(accountId, itemId, scope, c.signal)]).then(([value, history]) => { setItem(value); setVersions(history); setState("ready"); }).catch(() => { if (!c.signal.aborted) setState("error"); }); return () => c.abort(); }, [accountId, itemId, scope]);
  if (state === "loading") return <p>Loading external snapshot…</p>;
  if (state === "error" || !item) return <><h1>External snapshot unavailable</h1><p>No snapshot exists for that exact account and scope.</p><Link to="/external-context">Back to External Context</Link></>;
  async function previewImport() { setImportState("loading"); try { setImportPreview(await previewExternalItemImport(accountId, itemId, scope)); setImportState("preview"); } catch { setImportState("error"); } }
  async function confirmImport() { if (!importPreview) return; setImportState("loading"); try { setImportResult(await confirmExternalItemImport(accountId, itemId, scope, importPreview)); setImportState("success"); } catch { setImportState("conflict"); } }
  return <><header className="page-header"><p className="eyebrow">External / Untrusted · {item.reconciliation_state}</p><h1>{item.title}</h1><p>This quarantined text is rendered literally. It has no Agent, Automation, import, or Memory authority.</p></header><section className="panel"><h2>Snapshot</h2><pre className="external-content">{contentText(item)}</pre><dl className="detail-list"><div><dt>Immutable item identity</dt><dd>{item.external_item_id}</dd></div><div><dt>Immutable repository identity</dt><dd>{item.external_resource_id}</dd></div><div><dt>Application revision</dt><dd>{item.application_revision}</dd></div><div><dt>Provider source version</dt><dd>{item.provider_source_version}</dd></div><div><dt>First stored</dt><dd>{stamp(item.first_seen_at)}</dd></div><div><dt>This revision last observed</dt><dd>{stamp(item.revision_last_observed_at)}</dd></div><div><dt>Confirmed present through complete reconciliation</dt><dd>{stamp(item.confirmed_present_through)}</dd></div></dl>{item.source_url && <p><a href={item.source_url} target="_blank" rel="noreferrer">Open validated GitHub source</a></p>}</section><section className="panel"><h2>Import into audited local ingestion</h2><p><strong>Warning:</strong> This content is external and untrusted. Import copies exactly this snapshot into a local Source and SourceDocument. It does not create Memory or proposals.</p>{item.reconciliation_state === "current" && !importPreview && !importResult && <button type="button" disabled={importState === "loading"} onClick={() => void previewImport()}>Preview import</button>}{importPreview && !importResult && <div><h3>Exact import preview</h3><p>Revision {importPreview.application_revision} · {importPreview.resource_type.replace("_", " ")}</p><pre className="external-content">{importPreview.normalized_text}</pre><p>Content hash: {importPreview.content_hash}</p>{importPreview.canonical_source_url && <p>Canonical source: {importPreview.canonical_source_url}</p>}<button type="button" disabled={importState === "loading"} onClick={() => void confirmImport()}>Confirm exact import</button></div>}{importState === "error" && <p role="alert">This snapshot is not eligible for import.</p>}{importState === "conflict" && <p role="alert">The snapshot changed or is no longer eligible. Preview it again before importing.</p>}{importResult && <p role="status">Import {importResult.import_status}. <Link to={`/sources/${importResult.source_id}`}>Open resulting Source</Link></p>}</section><section className="panel"><h2>Revision history and provenance</h2><ol className="history-list">{versions.map(version => <li key={version.id}><h3>Revision {version.application_revision}{version.is_latest ? " · latest" : ""}</h3><p>Stored observation: {stamp(version.revision_last_observed_at)} · created by sync {version.created_sync_run_id}</p><pre className="external-content">{contentText(version)}</pre></li>)}</ol></section><Link to="/external-context">Back to External Context</Link></>;
}

export function ConnectorScheduleControls() {
  const [accountId, setAccountId] = useState("");
  const [schedule, setSchedule] = useState<ConnectorRefreshSchedule | null>(null);
  const [history, setHistory] = useState<ConnectorRefreshOccurrence[]>([]);
  const [time, setTime] = useState("08:00"), [zone, setZone] = useState("UTC"), [message, setMessage] = useState("");
  useEffect(() => { const c = new AbortController(); listConnectorAccounts(c.signal).then(values => { if (values[0]) setAccountId(values[0].id); }).catch(() => undefined); return () => c.abort(); }, []);
  useEffect(() => { if (!accountId) { setSchedule(null); setHistory([]); return; } const c = new AbortController(); getConnectorRefreshSchedule(accountId, c.signal).then(async value => { setSchedule(value); setHistory(await listConnectorRefreshOccurrences(value.id, c.signal)); }).catch(() => { if (!c.signal.aborted) { setSchedule(null); setHistory([]); } }); return () => c.abort(); }, [accountId]);
  async function create() { try { const value = await createConnectorRefreshSchedule(accountId, { schedule: { kind: "daily", timezone_name: zone, local_time: `${time}:00`, weekdays: [], interval_count: 1 }, missed_run_policy: "skip" }); setSchedule(value); setMessage("Draft created; scheduled refresh remains disabled."); } catch { setMessage("Schedule could not be created safely."); } }
  async function action(name: "enable" | "pause" | "resume" | "cancel") { if (!schedule) return; try { const value = await transitionConnectorRefreshSchedule(schedule.id, name, schedule.revision); setSchedule(value); setHistory(await listConnectorRefreshOccurrences(value.id)); setMessage(`Schedule ${name} completed.`); } catch { setMessage("Schedule changed; reload before retrying."); } }
  return <section className="panel"><h2>Scheduled GitHub refresh</h2><p>Scheduled refresh reads GitHub using the existing connector permissions. It does not run an Agent and does not import content.</p><p role="status">{message}</p>{!schedule ? <div className="filter-grid"><label htmlFor="connector-schedule-time">Daily time</label><input id="connector-schedule-time" type="time" value={time} onChange={event => setTime(event.target.value)} /><label htmlFor="connector-schedule-zone">IANA timezone</label><input id="connector-schedule-zone" value={zone} onChange={event => setZone(event.target.value)} /><button type="button" disabled={!accountId} onClick={() => void create()}>Create disabled schedule</button></div> : <><p>Status: {schedule.lifecycle}. Next: {stamp(schedule.next_occurrence_at)}</p><div className="actions">{schedule.lifecycle === "draft" && <button type="button" onClick={() => void action("enable")}>Enable explicitly</button>}{schedule.lifecycle === "enabled" && <button type="button" onClick={() => void action("pause")}>Pause</button>}{schedule.lifecycle === "paused" && <button type="button" onClick={() => void action("resume")}>Resume</button>}{schedule.lifecycle !== "cancelled" && <button type="button" onClick={() => void action("cancel")}>Cancel future scheduling</button>}</div><h3>Bounded safe history</h3>{history.length === 0 ? <p>No occurrences.</p> : <ul>{history.map(item => <li key={item.id}>{stamp(item.scheduled_at)} · {item.state} · {item.safe_disposition_code ?? item.safe_error_code ?? "no status code"}</li>)}</ul>}</>}</section>;
}
