import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ProposalDetail, Proposals } from "./Proposals";

const id = "11111111-1111-4111-8111-111111111111"; const source = "22222222-2222-4222-8222-222222222222"; const doc = "33333333-3333-4333-8333-333333333333"; const run = "44444444-4444-4444-8444-444444444444";
const item = { id, run_id: run, source_id: source, document_id: doc, source_chunk_id: null, project_id: null, proposal_index: 0, title: "Durable fact", summary: null, content: "public proposal content", memory_type: "semantic", importance: .5, confidence: .8, source_locator: null, review_status: "pending", review_note: null, reviewed_at: null, memory_id: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z", source_type: "note", source_name: "Notes", original_filename: null, run_provider: "fake", run_model: "fake", run_prompt_version: "v1" };
const detail = { ...item, source_chunk_hash: "a".repeat(64), evidence_text: "private evidence snapshot", evidence_char_start: 0, evidence_char_end: 25, proposal_hash: "b".repeat(64), run_status: "completed", source_chunk_available: false };
const response = (body: unknown, status = 200) => ({ ok: status >= 200 && status < 300, status, json: vi.fn().mockResolvedValue(body) } as unknown as Response);
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });
describe("proposal workflow", () => {
  it("renders real list data without evidence or N+1 requests and filters", async () => { const fetch = vi.fn().mockResolvedValue(response([item])); vi.stubGlobal("fetch", fetch); render(<MemoryRouter><Proposals /></MemoryRouter>); expect(await screen.findByText("public proposal content")).toBeInTheDocument(); expect(screen.queryByText("private evidence snapshot")).not.toBeInTheDocument(); expect(fetch).toHaveBeenCalledTimes(1); await userEvent.selectOptions(screen.getByLabelText("Review status"), "approved"); expect(fetch).toHaveBeenCalledTimes(2); });
  it("handles empty, failure and Retry", async () => { const fetch = vi.fn().mockResolvedValueOnce(response({}, 503)).mockResolvedValueOnce(response([])); vi.stubGlobal("fetch", fetch); render(<MemoryRouter><Proposals /></MemoryRouter>); await userEvent.click(await screen.findByRole("button", { name: "Retry" })); expect(await screen.findByText(/No proposals/)).toBeInTheDocument(); });
  it("renders evidence only on detail and requires confirmation before approve", async () => { const fetch = vi.fn().mockResolvedValue(response(detail)); vi.stubGlobal("fetch", fetch); vi.spyOn(window, "confirm").mockReturnValue(false); render(<MemoryRouter initialEntries={[`/proposals/${id}`]}><Routes><Route path="/proposals/:proposalId" element={<ProposalDetail/>}/></Routes></MemoryRouter>); expect(await screen.findByText("private evidence snapshot")).toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Approve" })); expect(window.confirm).toHaveBeenCalled(); expect(fetch).toHaveBeenCalledTimes(1); });
  it("handles malformed and missing IDs without exposing payloads", async () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); render(<MemoryRouter initialEntries={["/proposals/bad"]}><Routes><Route path="/proposals/:proposalId" element={<ProposalDetail/>}/></Routes></MemoryRouter>); expect(screen.getByRole("heading", { name: /Invalid proposal/ })).toBeInTheDocument(); expect(fetch).not.toHaveBeenCalled(); });
});
