import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ApiConflictError, getMemoryProposal, isSourceId, listMemoryProposals, promoteMemoryProposal, ProposalNotFoundError, reviewMemoryProposal, type MemoryProposal, type MemoryProposalDetail, type ReviewStatus } from "./api/client";

const PAGE = 20;
const date = (v: string | null) => v ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(v)) : "Not reviewed";
export function Proposals() {
  const [items, setItems] = useState<MemoryProposal[]>([]); const [status, setStatus] = useState<ReviewStatus | "all">("pending"); const [project, setProject] = useState(""); const [appliedProject, setAppliedProject] = useState(""); const [offset, setOffset] = useState(0); const [attempt, setAttempt] = useState(0); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [validation, setValidation] = useState("");
  useEffect(() => { const c = new AbortController(); setState("loading"); listMemoryProposals(status, appliedProject, PAGE, offset, c.signal).then(v => { setItems(v); setState("ready"); }).catch(() => { if (!c.signal.aborted) setState("error"); }); return () => c.abort(); }, [status, appliedProject, offset, attempt]);
  function apply() { if (project && !isSourceId(project)) { setValidation("Enter a valid Project UUID."); return; } setValidation(""); setOffset(0); setAppliedProject(project); }
  return <><header className="page-header"><p className="eyebrow">Human review</p><h1>Proposals</h1><p>Review generated knowledge before it becomes Memory.</p></header><section className="panel" aria-labelledby="filters-heading"><h2 id="filters-heading">Filters</h2><label htmlFor="proposal-status">Review status</label><select id="proposal-status" value={status} onChange={e => { setStatus(e.target.value as ReviewStatus | "all"); setOffset(0); }}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All</option></select><label htmlFor="proposal-project">Project UUID <span>(optional)</span></label><input id="proposal-project" value={project} onChange={e => setProject(e.target.value.trim())}/>{validation && <p role="alert" className="field-error">{validation}</p>}<button type="button" onClick={apply}>Apply filters</button></section><section className="panel" aria-live="polite" aria-busy={state === "loading"} aria-labelledby="queue-heading"><h2 id="queue-heading">Review queue</h2>{state === "loading" && <p>Loading proposals…</p>}{state === "error" && <><p>Proposals could not be loaded.</p><button type="button" onClick={() => setAttempt(v => v + 1)}>Retry</button></>}{state === "ready" && items.length === 0 && <p>No proposals match these filters.</p>}{state === "ready" && items.length > 0 && <ol className="proposal-list">{items.map(p => <li key={p.id}><h3><Link to={`/proposals/${p.id}`}>{p.title ?? "Untitled proposal"}</Link></h3><p>{p.content.length > 180 ? `${p.content.slice(0, 177)}…` : p.content}</p><p className="chunk-meta">Status: {p.review_status} · Confidence: {p.confidence} · Created: {date(p.created_at)}</p><p className="chunk-meta">Source: <Link to={`/sources/${p.source_id}`}>{p.source_name}</Link> · <Link to={`/source-documents/${p.document_id}`}>Document</Link>{p.project_id ? <> · <Link to={`/projects/${p.project_id}`}>Project</Link></> : null}</p></li>)}</ol>}<nav className="pagination" aria-label="Proposal pages"><button type="button" disabled={offset === 0 || state === "loading"} onClick={() => setOffset(Math.max(0, offset - PAGE))}>Previous</button><span>Page {offset / PAGE + 1}</span><button type="button" disabled={state === "loading" || items.length < PAGE} onClick={() => setOffset(offset + PAGE)}>Next</button></nav></section></>;
}

export function ProposalDetail() {
  const { proposalId = "" } = useParams(); const valid = isSourceId(proposalId); const [proposal, setProposal] = useState<MemoryProposalDetail | null>(null); const [state, setState] = useState<"loading" | "ready" | "error" | "missing" | "invalid">(valid ? "loading" : "invalid"); const [attempt, setAttempt] = useState(0); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [note, setNote] = useState(""); const statusRef = useRef<HTMLDivElement>(null); const active = useRef<AbortController | null>(null);
  useEffect(() => { if (!valid) return; const c = new AbortController(); active.current = c; setState("loading"); getMemoryProposal(proposalId, c.signal).then(v => { setProposal(v); setState("ready"); }).catch(e => { if (!c.signal.aborted) setState(e instanceof ProposalNotFoundError ? "missing" : "error"); }); return () => c.abort(); }, [proposalId, valid, attempt]);
  async function act(kind: "approve" | "reject" | "promote") { if (busy || !proposal) return; if (kind === "reject" && !note.trim()) { setMessage("Enter a rejection note."); document.getElementById("review-note")?.focus(); return; } if (!window.confirm(`Confirm ${kind} proposal?`)) return; const c = new AbortController(); active.current?.abort(); active.current = c; setBusy(true); setMessage(""); try { if (kind === "promote") await promoteMemoryProposal(proposal.id, c.signal); else await reviewMemoryProposal(proposal.id, kind, kind === "reject" ? note.trim() : note.trim() || null, c.signal); const fresh = await getMemoryProposal(proposal.id, c.signal); setProposal(fresh); setMessage(`${kind === "promote" ? "Promotion" : "Review"} completed.`); setTimeout(() => statusRef.current?.focus(), 0); } catch (e) { if (!c.signal.aborted) setMessage(e instanceof ApiConflictError ? "The proposal changed. Refresh and try again." : "The action could not be completed safely."); } finally { if (!c.signal.aborted) setBusy(false); } }
  if (!valid || state === "invalid") return <section className="panel"><h1>Invalid proposal address</h1><p>The proposal identifier is malformed.</p></section>;
  return <><header className="page-header"><p className="eyebrow">Proposal review</p><h1>{proposal?.title ?? "Proposal detail"}</h1></header><section className="panel" aria-live="polite" aria-busy={state === "loading"}>{state === "loading" && <p>Loading proposal…</p>}{state === "missing" && <><h2>Proposal not found</h2><p>The requested proposal does not exist.</p></>}{state === "error" && <><h2>Proposal unavailable</h2><button type="button" onClick={() => setAttempt(v => v + 1)}>Retry</button></>}{state === "ready" && proposal && <><div ref={statusRef} tabIndex={-1} aria-label="Current proposal status"><strong>Status: {proposal.review_status}</strong>{proposal.memory_id && <> · Memory {proposal.memory_id}</>}</div>{message && <p role="status">{message}</p>}<h2>Proposed Memory</h2><p className="evidence">{proposal.content}</p><dl className="detail-list"><div><dt>Summary</dt><dd>{proposal.summary ?? "Not supplied"}</dd></div><div><dt>Type</dt><dd>{proposal.memory_type}</dd></div><div><dt>Importance / confidence</dt><dd>{proposal.importance} / {proposal.confidence}</dd></div><div><dt>Created / reviewed / updated</dt><dd>{date(proposal.created_at)} / {date(proposal.reviewed_at)} / {date(proposal.updated_at)}</dd></div><div><dt>Run</dt><dd>{proposal.run_id} · {proposal.run_status} · {proposal.run_provider} / {proposal.run_model} / {proposal.run_prompt_version}</dd></div><div><dt>Provenance</dt><dd><Link to={`/sources/${proposal.source_id}`}>Source</Link> · <Link to={`/source-documents/${proposal.document_id}`}>Document</Link>{proposal.source_chunk_id ? ` · Chunk ${proposal.source_chunk_id}` : " · Source chunk unavailable"}{proposal.source_locator ? ` · ${proposal.source_locator}` : ""}</dd></div><div><dt>Review note</dt><dd>{proposal.review_note ?? "None"}</dd></div></dl><section aria-labelledby="evidence-heading"><h2 id="evidence-heading">Evidence snapshot</h2><pre className="evidence">{proposal.evidence_text}</pre><p className="chunk-meta">Characters {proposal.evidence_char_start}–{proposal.evidence_char_end} · Snapshot hash {proposal.source_chunk_hash}</p></section>{proposal.review_status === "pending" && <><label htmlFor="review-note">Review note <span>(required for rejection)</span></label><textarea id="review-note" value={note} disabled={busy} onChange={e => setNote(e.target.value)} maxLength={2000}/><div className="actions"><button disabled={busy} type="button" onClick={() => act("approve")}>Approve</button><button disabled={busy} type="button" onClick={() => act("reject")}>Reject</button></div></>}{proposal.review_status === "approved" && !proposal.memory_id && <button disabled={busy} type="button" onClick={() => act("promote")}>Promote to Memory</button>}<Link className="back-link" to="/proposals">Back to proposals</Link></>}</section></>;
}
