import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router";
import { afterEach, describe, expect, it, vi } from "vitest";
import { Search } from "./Search";

const ID1 = "11111111-1111-4111-8111-111111111111";
const ID2 = "22222222-2222-4222-8222-222222222222";
const PROJECT = "33333333-3333-4333-8333-333333333333";
const memory = (id: string, title: string) => ({ id, project_id: PROJECT, content: `${title} full content`, source: null, title, summary: `${title} summary`, memory_type: "semantic", importance: .7, confidence: .8, status: "active", event_time: null, expires_at: null, supersedes_id: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" });
const response = (body: unknown, status = 200): Response => ({ ok: status >= 200 && status < 300, status, json: vi.fn().mockResolvedValue(body) } as unknown as Response);
function page() { return render(<MemoryRouter><Search /></MemoryRouter>); }
async function fill(query = "needle") { await userEvent.type(screen.getByLabelText("Query"), query); }
afterEach(() => { cleanup(); vi.unstubAllGlobals(); vi.restoreAllMocks(); });

describe("Search", () => {
  it("does not request before explicit submission and validates the first invalid field", async () => { const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock); page(); await fill("draft"); await userEvent.clear(screen.getByLabelText("Query")); expect(fetchMock).not.toHaveBeenCalled(); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(await screen.findByRole("alert")).toHaveTextContent("Enter a search query"); expect(screen.getByLabelText("Query")).toHaveFocus(); expect(fetchMock).not.toHaveBeenCalled(); });
  it("uses the exact lexical contract and preserves backend order without N+1 reads", async () => { const fetchMock = vi.fn().mockResolvedValue(response([memory(ID2, "Second"), memory(ID1, "First")])); vi.stubGlobal("fetch", fetchMock); page(); await fill(); await userEvent.type(screen.getByLabelText(/Project UUID/), PROJECT); await userEvent.selectOptions(screen.getByLabelText(/Memory type/), "semantic"); await userEvent.selectOptions(screen.getByLabelText(/Status/), "active"); await userEvent.type(screen.getByLabelText(/Minimum confidence/), "0.5"); await userEvent.type(screen.getByLabelText(/Maximum importance/), "0.9"); await userEvent.clear(screen.getByLabelText("Limit")); await userEvent.type(screen.getByLabelText("Limit"), "10"); await userEvent.click(screen.getByRole("button", { name: "Search" })); const links = await screen.findAllByRole("link"); expect(links.map(link => link.textContent)).toEqual(["Second", "First"]); expect(links[0]).toHaveAttribute("href", `/memories/${ID2}`); expect(fetchMock).toHaveBeenCalledTimes(1); expect(fetchMock.mock.calls[0][0]).toBe(`/api/memories?query=needle&limit=10&offset=0&project_id=${PROJECT}&memory_type=semantic&status=active&importance_max=0.9&confidence_min=0.5`); expect(screen.getByText(/Scores are not exposed/)).toBeInTheDocument(); });
  it.each(["semantic", "hybrid"] as const)("uses the exact %s contract with no fallback", async mode => { const fetchMock = vi.fn().mockResolvedValue(response([])); vi.stubGlobal("fetch", fetchMock); page(); await fill("  meaning  "); await userEvent.selectOptions(screen.getByLabelText("Search mode"), mode); await userEvent.click(screen.getByRole("button", { name: "Search" })); await screen.findByText(/No Memories matched/); const [url, init] = fetchMock.mock.calls[0] as [string, RequestInit]; expect(url).toBe("/api/memories/search"); expect(JSON.parse(String(init.body))).toEqual({ query: "meaning", mode, filters: {}, pagination: { limit: 20, offset: 0 } }); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("validates request limits locally", async () => { const fetchMock = vi.fn(); vi.stubGlobal("fetch", fetchMock); page(); await fill(); await userEvent.clear(screen.getByLabelText("Limit")); await userEvent.type(screen.getByLabelText("Limit"), "101"); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(await screen.findByRole("alert")).toHaveTextContent("1 to 100"); expect(screen.getByLabelText("Limit")).toHaveFocus(); expect(fetchMock).not.toHaveBeenCalled(); });
  it("rejects malformed payloads safely and retries only the last submission", async () => { const fetchMock = vi.fn().mockResolvedValueOnce(response([{ vector: [1, 2], evidence: "secret" }])).mockResolvedValueOnce(response([])); vi.stubGlobal("fetch", fetchMock); page(); await fill(); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(await screen.findByRole("alert")).toHaveTextContent("safely"); expect(screen.queryByText("secret")).not.toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Retry" })); await screen.findByText(/No Memories matched/); expect(fetchMock).toHaveBeenCalledTimes(2); expect(fetchMock.mock.calls[1][0]).toBe(fetchMock.mock.calls[0][0]); });
  it("shows whitelisted provider errors without leaking raw details", async () => { const fetchMock = vi.fn().mockResolvedValue(response({ detail: "embedding provider unavailable", api_key: "secret" }, 503)); vi.stubGlobal("fetch", fetchMock); page(); await fill(); await userEvent.selectOptions(screen.getByLabelText("Search mode"), "semantic"); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(await screen.findByRole("alert")).toHaveTextContent("not configured"); expect(screen.queryByText(/secret|api_key/)).not.toBeInTheDocument(); expect(fetchMock).toHaveBeenCalledTimes(1); });
  it("prevents duplicate submission while active", async () => { const fetchMock = vi.fn(() => new Promise<Response>(() => undefined)); vi.stubGlobal("fetch", fetchMock); page(); await fill(); await userEvent.dblClick(screen.getByRole("button", { name: "Search" })); expect(fetchMock).toHaveBeenCalledTimes(1); expect(screen.getByRole("button", { name: "Searching…" })).toBeDisabled(); });
  it("aborts obsolete work and keeps the latest submitted request authoritative", async () => { const pending: Array<{ signal: AbortSignal; resolve: (value: Response) => void }> = []; const fetchMock = vi.fn((_url: string, init: RequestInit) => new Promise<Response>(resolve => pending.push({ signal: init.signal as AbortSignal, resolve }))); vi.stubGlobal("fetch", fetchMock); page(); await fill("first"); await userEvent.click(screen.getByRole("button", { name: "Search" })); pending[0].resolve(response([memory(ID1, "Old")])); await screen.findByText("Old"); await userEvent.clear(screen.getByLabelText("Query")); await fill("second"); await userEvent.click(screen.getByRole("button", { name: "Search" })); expect(fetchMock).toHaveBeenCalledTimes(2); pending[1].resolve(response([memory(ID2, "New")])); expect(await screen.findByText("New")).toBeInTheDocument(); await waitFor(() => expect(screen.queryByText("Old")).not.toBeInTheDocument()); });
});
